import * as z from "zod/v4";

export const NextFactoryControlInputSchema = z.discriminatedUnion("action",[
        z.object({
          action:z.literal("create_mission"),
          args:z.object({
            mission_input:z.object({
              execution_profile:z.enum(["PRODUCTION","DEMO_BOUNDED"])
            }).passthrough()
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("status"),
          args:z.object({mission_id:z.string().min(1).max(128)}).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("get_work"),
          args:z.object({mission_id:z.string().min(1).max(128)}).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("submit_phase"),
          args:z.discriminatedUnion("phase",[
            z.object({
              mission_id:z.string().min(1).max(128),
              expected_state_version:z.number().int().min(1),
              phase:z.literal("H1"),
              payload:z.object({
                unknowns:z.array(z.unknown()),
                conflicts:z.array(z.unknown()),
                mission_truth:z.record(z.string(),z.unknown())
              }).strict()
            }).strict(),
            z.object({
              mission_id:z.string().min(1).max(128),
              expected_state_version:z.number().int().min(1),
              phase:z.literal("H2"),
              payload:z.object({
                blueprint_revision:z.number().int().min(1),
                product_decomposition:z.record(z.string(),z.unknown()),
                system_blueprint:z.record(z.string(),z.unknown())
              }).strict()
            }).strict(),
            z.object({
              mission_id:z.string().min(1).max(128),
              expected_state_version:z.number().int().min(1),
              phase:z.literal("H3"),
              payload:z.object({
                packet_id:z.string().min(1),
                fork_readiness:z.record(z.string(),z.unknown()),
                kit_orders:z.record(z.string(),z.unknown())
              }).strict()
            }).strict()
          ]),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("attempt_fork"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            orders:z.array(z.record(z.string(),z.unknown())).length(3)
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("list_work_items"),
          args:z.object({mission_id:z.string().min(1).max(128)}).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("claim_work"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            work_item_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            owner:z.string().min(1)
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("reassign_work"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            work_item_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            new_owner:z.string().min(1),
            reason:z.string().min(1)
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("checkpoint"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            work_item_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            owner_epoch:z.number().int().min(0),
            checkpoint:z.record(z.string(),z.unknown()).optional()
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("report_defect"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            work_item_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            owner_epoch:z.number().int().min(0),
            classification:z.string().min(1).optional(),
            evidence:z.record(z.string(),z.unknown()).optional()
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("barrier_review"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            defect_id:z.string().min(1).max(128),
            repair_succeeded:z.boolean().optional(),
            repair_evidence:z.array(z.unknown()).optional()
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("human_recovery"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            defect_id:z.string().min(1).max(128),
            choice:z.string().min(1),
            reason:z.string().optional(),
            verified:z.boolean().optional(),
            accepted_risk:z.array(z.unknown()).optional()
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("record_capability_contribution"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            work_item_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            owner_epoch:z.number().int().min(0),
            capability_id:z.string().min(1),
            contribution_result:z.record(z.string(),z.unknown()),
            evidence_refs:z.array(z.string().min(1)).min(1)
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("package_work"),
          args:z.object({
            mission_id:z.string().min(1).max(128),
            work_item_id:z.string().min(1).max(128),
            expected_state_version:z.number().int().min(1),
            owner_epoch:z.number().int().min(0),
            manifest:z.record(z.string(),z.unknown())
          }).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        }),
        z.object({
          action:z.literal("compose_readiness"),
          args:z.object({mission_id:z.string().min(1).max(128)}).strict(),
          role:z.enum(["client","operator","unspecified"]).default("unspecified"),
          locale:z.string().min(2).max(32).default("vi-VN")
        })
      ]);
